[package]
name          = "show-image"
version       = "0.6.2"
license       = "BSD-2-Clause"
description   = "quickly show images in a window for debugging"
edition       = "2018"

repository    = "https://github.com/robohouse-delft/show-image-rs"
documentation = "https://docs.rs/show-image"
readme        = "README.md"

authors = [
	"Maarten de Vries <maarten@de-vri.es>",
	"Hans Gaiser <hans.gaiser@robovalley.com>",
	"RoboHouse <robohouse@robovalley.com>",
]

keywords = ["image", "visualize", "show", "debug"]
categories = [
	"development-tools::debugging",
	"multimedia::images",
	"visualization",
	"gui",
]

[features]
full     = ["save", "image", "tch", "raqote"]
save     = ["tinyfiledialogs", "image"]
doc-only = ["tch/doc-only"]

[dependencies]
euclid          = "0.20.8"
keyboard-types  = "0.5.0"
sdl2            = "0.33.0"
image           = { version="0.23.0", optional=true }
raqote          = { version="0.7.14", optional=true }
tch             = { version="0.1.6",  optional=true }
tinyfiledialogs = { version="3.3.9",  optional=true }

[dev-dependencies]
show-image = { path = ".", features=["full"] }
assert2    = "0.1.1"

[package.metadata.docs.rs]
features = ["doc-only", "full"]
